In [ ]:
import pandas as pd
df = pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  31978 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

(32561, 15)

In [8]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [9]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [10]:
df['workclass'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', nan, ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [11]:
df['occupation'].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', nan, ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [12]:
df['native_country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', nan, ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [13]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [14]:
df.replace(' ?', pd.NA, inplace=True)

In [15]:
mode_value = df['workclass'].mode()[0]
df['workclass'].fillna(mode_value, inplace = True)

In [16]:
df['workclass'].isnull().sum()

np.int64(0)

In [17]:
mode_value = df['occupation'].mode()[0]
df['occupation'].fillna(mode_value, inplace = True)

C:\Users\12474\AppData\Local\Temp\ipykernel_22728\3339212781.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['occupation'].fillna(mode_value, inplace = True)

In [19]:
mode_value = df['workclass'].mode()[0]
df['workclass'].fillna(mode_value, inplace = True)

In [20]:
mode_value = df['native_country'].mode()[0]
df['native_country'].fillna(mode_value, inplace = True)

C:\Users\12474\AppData\Local\Temp\ipykernel_22728\1756129725.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['native_country'].fillna(mode_value, inplace = True)

In [21]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [22]:
df.drop(['fnlwgt', 'education'], axis = 1, inplace = True)

In [23]:
df.columns

Index(['age', 'workclass', 'education_num', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
       'hours_per_week', 'native_country', 'income'],
      dtype='object')

In [24]:
df['sex'] = df['sex'].map({
    ' Male':1,
    ' Female':0
})

In [25]:
df['sex'].head()

0    1
1    1
2    1
3    1
4    0
Name: sex, dtype: int64

In [26]:
df = pd.get_dummies(df, columns=['workclass'])

In [27]:
df.head()

,age,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,workclass_ Without-pay
0,39,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40,United-States,<=50K,False,False,False,False,False,False,True,False
1,50,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13,United-States,<=50K,False,False,False,False,False,True,False,False
2,38,9,Divorced,Handlers-cleaners,Not-in-family,White,1,0,0,40,United-States,<=50K,False,False,False,True,False,False,False,False
3,53,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,1,0,0,40,United-States,<=50K,False,False,False,True,False,False,False,False
4,28,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,0,40,Cuba,<=50K,False,False,False,True,False,False,False,False

In [28]:
df['income'] = df['income'].map({
    ' <=50k':0,
    ' >50k':1
})

In [29]:
df['income'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: income, dtype: float64

In [30]:
df['income'].unique()

array([nan])

In [31]:
import pandas as pd

df = pd.read_csv("adult.csv")

In [32]:
df.replace(' ?', pd.NA, inplace=True)

In [33]:
df['workclass'].fillna(df['workclass'].mode()[0], inplace=True)

df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)

df['native_country'].fillna(df['native_country'].mode()[0], inplace=True)

C:\Users\12474\AppData\Local\Temp\ipykernel_22728\799033823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['workclass'].fillna(df['workclass'].mode()[0], inplace=True)
C:\Users\12474\AppData\Local\Temp\ipykernel_22728\799033823.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)
C:\Users\12474\AppData\Local\Temp\ipykernel_22728\799033823.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['native_country'].fillna(df['native_country'].mode()[0], inplace=True)

In [34]:
df.drop(['fnlwgt', 'education'], axis=1, inplace=True)

In [35]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [36]:
df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [37]:
df['income'] = df['income'].map({
    '<=50K': 0,
    '>50K': 1
})

In [38]:
df['income'].head()

0    0
1    0
2    0
3    0
4    0
Name: income, dtype: int64

In [39]:
df['sex'] = df['sex'].map({
    'Male': 1,
    'Female': 0
})

In [40]:
df['sex'].head()

0    1
1    1
2    1
3    1
4    0
Name: sex, dtype: int64

In [41]:
df.head()

,age,workclass,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40,United-States,0
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13,United-States,0
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,White,1,0,0,40,United-States,0
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,1,0,0,40,United-States,0
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,0,40,Cuba,0

In [42]:
categorical_cols = [
    'workclass',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'native_country'
]

In [43]:
df = pd.get_dummies(df, columns=categorical_cols)

In [44]:
df.head()

,age,education_num,sex,capital_gain,capital_loss,hours_per_week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,13,1,2174,0,40,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50,13,1,0,0,13,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38,9,1,0,0,40,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53,7,1,0,0,40,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,28,13,0,0,0,40,0,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [45]:
from sklearn.preprocessing import StandardScaler

In [48]:
numeric_cols = [
    'age',
    'education_num',
    'capital_gain',
    'capital_loss',
    'hours_per_week'
]

In [49]:
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [50]:
df.head()

,age,education_num,sex,capital_gain,capital_loss,hours_per_week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,0.030671,1.134739,1,0.148453,-0.21666,-0.035429,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0.837109,1.134739,1,-0.145920,-0.21666,-2.222153,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,-0.042642,-0.420060,1,-0.145920,-0.21666,-0.035429,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,1.057047,-1.197459,1,-0.145920,-0.21666,-0.035429,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,-0.775768,1.134739,0,-0.145920,-0.21666,-0.035429,0,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [51]:
x = df.drop('income', axis=1)
y = df['income']

In [52]:
from sklearn.decomposition import PCA

In [54]:
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)

In [55]:
x_pca.shape

(32561, 2)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test = train_test_split(
    x_pca,
    y,
    test_size=0.2,
    random_state=42
)

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
model = LogisticRegression()

In [60]:
model.fit(x_train, y_train)

LogisticRegression()

In [61]:
y_pred = model.predict(x_test)

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.8195915860586519